/*
Pitágoras Alves & André Winston, UFRN, March 2017.

string run(const char * command):
  command   Shell command to be executed by linux;
  returns   A string with all of the output generated by the command
string run(string command):
  same as above
void runWhileSilent(vector<string> commands):
  commands  Vector of commands to be executed in sequence. If one of the commands
            outputs anything, the commands after him will be canceled.
*/
#ifndef _RUN_
#define _RUN_

#include <iostream>
#include <stdexcept>
#include <stdio.h>
#include <string>
#include <unistd.h>
#include <set>
#include <signal.h>
#include <vector>
#include <thread>

using namespace std;

void runWhileSilent(vector<string> commands);
string runStr(string command);
string run(const char* command);
void runAsync(const char* command);

#endif
